### ISSUE TITLE
[docker] xxljob

### ISSUE THREAD

**Issue by Alice52** [Alice52/job#4]
1. xxl-job [admin](https://registry.hub.docker.com/r/huahouye/xxl-job-admin)

```yml
version: '3.0'
services:
  xxl-job-admin:
    image: registry.cn-shanghai.aliyuncs.com/alice52/xxl-job-admin:2.3.1
    restart: 'on-failure:3'
    container_name: dev-xxl-job-admin
    ports:
      - 9090:8080
    volumes:      
      - /root/xxl-job/admin/logs:/logs
      
  
  xxl-job-executor:
    image: registry.cn-shanghai.aliyuncs.com/alice52/boot-boot-job-xxl-job:20210516.5c6e021
    restart: 'on-failure:3'
    container_name: dev-xxl-job-executor
    ports:
      - 9091:8080
    volumes:      
      - /root/xxl-job/executor/logs:/logs
    environment:
      - spring.profiles.active=cloud
      - xxl.job.admin.address=http://xxl-job-admin:8080/xxl-job-admin
```
